"""
QUANT_INDUSTRY_V1 Strategy Base

Base strategy framework with:
- Strategy lifecycle management
- Performance attribution
- Signal generation interface
- Backtesting support

Rollback Plan: Delete this file
Tests Required: Strategy execution, signal generation
Failure Modes: Disable strategy, alert operators
"""

import numpy as np
import logging
from datetime import datetime, timezone
from typing import Optional, Dict, Any, List, Tuple, Callable
from dataclasses import dataclass, field
from enum import Enum
from abc import ABC, abstractmethod
import uuid

logger = logging.getLogger(__name__)


# =============================================================================
# STRATEGY TYPES
# =============================================================================

class StrategyStatus(Enum):
    """Strategy lifecycle status."""
    DRAFT = "draft"
    BACKTESTING = "backtesting"
    PAPER = "paper"
    LIVE = "live"
    PAUSED = "paused"
    RETIRED = "retired"


class SignalDirection(Enum):
    """Signal direction."""
    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    strategy_id: str = ""
    symbol: str = ""
    direction: SignalDirection = SignalDirection.FLAT
    strength: float = 0.0  # -1 to 1
    confidence: float = 0.0  # 0 to 1
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    expiry: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            'signal_id': self.signal_id,
            'strategy_id': self.strategy_id,
            'symbol': self.symbol,
            'direction': self.direction.value,
            'strength': self.strength,
            'confidence': self.confidence,
            'entry_price': self.entry_price,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'expiry': self.expiry.isoformat() if self.expiry else None,
            'metadata': self.metadata,
            'generated_at': self.generated_at.isoformat(),
        }


@dataclass
class StrategyConfig:
    """Strategy configuration."""
    name: str = "Unnamed Strategy"
    description: str = ""
    version: str = "1.0.0"
    symbols: List[str] = field(default_factory=list)
    timeframe: str = "1d"
    parameters: Dict[str, Any] = field(default_factory=dict)
    risk_params: Dict[str, Any] = field(default_factory=dict)
    enabled: bool = True


@dataclass
class StrategyMetrics:
    """Strategy performance metrics."""
    total_signals: int = 0
    winning_signals: int = 0
    losing_signals: int = 0
    total_return: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    calmar_ratio: float = 0.0
    sortino_ratio: float = 0.0
    information_ratio: float = 0.0
    beta: float = 0.0
    alpha: float = 0.0

    def to_dict(self) -> Dict[str, float]:
        return {
            'total_signals': self.total_signals,
            'winning_signals': self.winning_signals,
            'losing_signals': self.losing_signals,
            'total_return': self.total_return,
            'sharpe_ratio': self.sharpe_ratio,
            'max_drawdown': self.max_drawdown,
            'win_rate': self.win_rate,
            'profit_factor': self.profit_factor,
            'avg_win': self.avg_win,
            'avg_loss': self.avg_loss,
            'calmar_ratio': self.calmar_ratio,
            'sortino_ratio': self.sortino_ratio,
        }


# =============================================================================
# BASE STRATEGY
# =============================================================================

class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.

    Implement generate_signals() for custom strategy logic.
    """

    def __init__(self, config: StrategyConfig = None):
        self.config = config or StrategyConfig()
        self.strategy_id = str(uuid.uuid4())[:8]
        self.status = StrategyStatus.DRAFT

        # State
        self.positions: Dict[str, float] = {}
        self.signals_generated: List[Signal] = []

        # Performance tracking
        self.metrics = StrategyMetrics()
        self.equity_curve: List[float] = []
        self.returns: List[float] = []

        # Callbacks
        self.on_signal: List[Callable[[Signal], None]] = []

    @abstractmethod
    def generate_signals(
        self,
        data: Dict[str, Any],
        features: Dict[str, np.ndarray] = None,
        regime: str = None
    ) -> List[Signal]:
        """
        Generate trading signals.

        Args:
            data: Market data dictionary with OHLCV
            features: Computed features
            regime: Current market regime

        Returns:
            List of Signal objects
        """
        pass

    def initialize(self) -> None:
        """Initialize strategy (called before first run)."""
        pass

    def update(self, data: Dict[str, Any]) -> List[Signal]:
        """
        Update strategy with new data and generate signals.

        Args:
            data: New market data

        Returns:
            List of new signals
        """
        if self.status not in [StrategyStatus.LIVE, StrategyStatus.PAPER, StrategyStatus.BACKTESTING]:
            return []

        signals = self.generate_signals(data)

        for signal in signals:
            signal.strategy_id = self.strategy_id
            self.signals_generated.append(signal)

            # Notify handlers
            for handler in self.on_signal:
                try:
                    handler(signal)
                except Exception as e:
                    logger.error(f"Signal handler error: {e}")

        return signals

    def record_trade_result(
        self,
        signal: Signal,
        entry_price: float,
        exit_price: float,
        pnl: float
    ) -> None:
        """Record trade result for performance tracking."""
        self.returns.append(pnl)
        self.metrics.total_signals += 1

        if pnl > 0:
            self.metrics.winning_signals += 1
            self.metrics.avg_win = (
                (self.metrics.avg_win * (self.metrics.winning_signals - 1) + pnl) /
                self.metrics.winning_signals
            )
        else:
            self.metrics.losing_signals += 1
            self.metrics.avg_loss = (
                (self.metrics.avg_loss * (self.metrics.losing_signals - 1) + abs(pnl)) /
                self.metrics.losing_signals
            ) if self.metrics.losing_signals > 0 else abs(pnl)

        # Update win rate
        if self.metrics.total_signals > 0:
            self.metrics.win_rate = self.metrics.winning_signals / self.metrics.total_signals

        # Update profit factor
        if self.metrics.avg_loss > 0:
            self.metrics.profit_factor = self.metrics.avg_win / self.metrics.avg_loss

        # Update total return
        self.metrics.total_return = sum(self.returns)

        # Update equity curve
        if self.equity_curve:
            self.equity_curve.append(self.equity_curve[-1] + pnl)
        else:
            self.equity_curve.append(pnl)

        # Update drawdown
        self._update_drawdown()

    def _update_drawdown(self) -> None:
        """Update max drawdown metric."""
        if not self.equity_curve:
            return

        equity = np.array(self.equity_curve)
        peak = np.maximum.accumulate(equity)
        drawdown = (peak - equity) / (peak + 1e-8)
        self.metrics.max_drawdown = float(np.max(drawdown))

    def calculate_sharpe(self, risk_free_rate: float = 0.02) -> float:
        """Calculate Sharpe ratio."""
        if len(self.returns) < 2:
            return 0.0

        returns_arr = np.array(self.returns)
        mean_ret = np.mean(returns_arr)
        std_ret = np.std(returns_arr)

        if std_ret < 1e-8:
            return 0.0

        daily_rf = risk_free_rate / 252
        self.metrics.sharpe_ratio = float(np.sqrt(252) * (mean_ret - daily_rf) / std_ret)

        return self.metrics.sharpe_ratio

    def get_state(self) -> Dict[str, Any]:
        """Get strategy state for persistence."""
        return {
            'strategy_id': self.strategy_id,
            'config': {
                'name': self.config.name,
                'version': self.config.version,
                'parameters': self.config.parameters,
            },
            'status': self.status.value,
            'metrics': self.metrics.to_dict(),
            'positions': self.positions.copy(),
            'signals_count': len(self.signals_generated),
        }

    def set_status(self, status: StrategyStatus) -> None:
        """Set strategy status."""
        old_status = self.status
        self.status = status
        logger.info(f"Strategy {self.config.name}: {old_status.value} -> {status.value}")


# =============================================================================
# STRATEGY REGISTRY
# =============================================================================

class StrategyRegistry:
    """
    Registry for strategy management.

    Tracks all strategies and their performance.
    """

    def __init__(self):
        self.strategies: Dict[str, BaseStrategy] = {}
        self.strategy_history: List[Dict[str, Any]] = []

    def register(self, strategy: BaseStrategy) -> str:
        """Register a strategy."""
        self.strategies[strategy.strategy_id] = strategy
        logger.info(f"Registered strategy: {strategy.config.name} ({strategy.strategy_id})")
        return strategy.strategy_id

    def unregister(self, strategy_id: str) -> bool:
        """Unregister a strategy."""
        if strategy_id in self.strategies:
            strategy = self.strategies[strategy_id]
            strategy.set_status(StrategyStatus.RETIRED)

            # Save history
            self.strategy_history.append(strategy.get_state())

            del self.strategies[strategy_id]
            return True
        return False

    def get(self, strategy_id: str) -> Optional[BaseStrategy]:
        """Get strategy by ID."""
        return self.strategies.get(strategy_id)

    def get_active(self) -> List[BaseStrategy]:
        """Get all active strategies."""
        return [
            s for s in self.strategies.values()
            if s.status in [StrategyStatus.LIVE, StrategyStatus.PAPER]
        ]

    def get_by_status(self, status: StrategyStatus) -> List[BaseStrategy]:
        """Get strategies by status."""
        return [s for s in self.strategies.values() if s.status == status]

    def get_best_performers(
        self,
        metric: str = 'sharpe_ratio',
        top_n: int = 5
    ) -> List[BaseStrategy]:
        """Get top performing strategies."""
        strategies = list(self.strategies.values())
        strategies.sort(
            key=lambda s: getattr(s.metrics, metric, 0),
            reverse=True
        )
        return strategies[:top_n]

    def compare_strategies(self) -> Dict[str, Dict[str, float]]:
        """Compare all strategies by metrics."""
        return {
            s.config.name: s.metrics.to_dict()
            for s in self.strategies.values()
        }


# =============================================================================
# EXAMPLE STRATEGIES
# =============================================================================

class MomentumStrategy(BaseStrategy):
    """Simple momentum strategy."""

    def __init__(self, config: StrategyConfig = None):
        if config is None:
            config = StrategyConfig(
                name="Momentum Strategy",
                parameters={
                    'lookback': 20,
                    'threshold': 0.02,
                }
            )
        super().__init__(config)

    def generate_signals(
        self,
        data: Dict[str, Any],
        features: Dict[str, np.ndarray] = None,
        regime: str = None
    ) -> List[Signal]:
        signals = []

        for symbol in self.config.symbols or data.keys():
            if symbol not in data:
                continue

            prices = data[symbol].get('close', [])
            if len(prices) < self.config.parameters.get('lookback', 20):
                continue

            lookback = self.config.parameters['lookback']
            threshold = self.config.parameters.get('threshold', 0.02)

            # Calculate momentum
            momentum = (prices[-1] - prices[-lookback]) / prices[-lookback]

            # Generate signal
            if abs(momentum) > threshold:
                direction = SignalDirection.LONG if momentum > 0 else SignalDirection.SHORT
                signal = Signal(
                    strategy_id=self.strategy_id,
                    symbol=symbol,
                    direction=direction,
                    strength=np.tanh(momentum * 10),  # Normalize to [-1, 1]
                    confidence=min(1.0, abs(momentum) / 0.1),
                    entry_price=prices[-1],
                    metadata={'momentum': momentum},
                )
                signals.append(signal)

        return signals


class MeanReversionStrategy(BaseStrategy):
    """Mean reversion strategy."""

    def __init__(self, config: StrategyConfig = None):
        if config is None:
            config = StrategyConfig(
                name="Mean Reversion Strategy",
                parameters={
                    'lookback': 20,
                    'zscore_threshold': 2.0,
                }
            )
        super().__init__(config)

    def generate_signals(
        self,
        data: Dict[str, Any],
        features: Dict[str, np.ndarray] = None,
        regime: str = None
    ) -> List[Signal]:
        signals = []

        for symbol in self.config.symbols or data.keys():
            if symbol not in data:
                continue

            prices = data[symbol].get('close', [])
            lookback = self.config.parameters.get('lookback', 20)

            if len(prices) < lookback:
                continue

            # Calculate z-score
            recent = np.array(prices[-lookback:])
            mean = np.mean(recent)
            std = np.std(recent)

            if std < 1e-8:
                continue

            zscore = (prices[-1] - mean) / std
            threshold = self.config.parameters.get('zscore_threshold', 2.0)

            # Generate signal (opposite to z-score)
            if abs(zscore) > threshold:
                direction = SignalDirection.SHORT if zscore > 0 else SignalDirection.LONG
                signal = Signal(
                    strategy_id=self.strategy_id,
                    symbol=symbol,
                    direction=direction,
                    strength=-np.tanh(zscore / 3),  # Opposite direction
                    confidence=min(1.0, abs(zscore) / 4),
                    entry_price=prices[-1],
                    stop_loss=mean,  # Stop at mean
                    metadata={'zscore': zscore, 'mean': mean, 'std': std},
                )
                signals.append(signal)

        return signals
