"""
ML Risk Predictor - Integration with Real-Time Risk Engine

This module integrates the ML risk prediction model with the real-time
risk monitoring system for proactive risk management.

Key Features:
- Real-time risk prediction updates
- Integration with position sizing
- Automatic risk limit adjustment
- Alert generation for high-risk predictions
- Historical prediction tracking

Architecture:
    Market Data Stream
        → ML Risk Prediction Model
        → Risk Predictor Integration
            ├── Real-Time Monitor Updates
            ├── Position Sizing Adjustments
            ├── Alert Generation
            └── Dashboard Updates

Usage:
    from backend.risk.ml_risk_predictor import MLRiskPredictor

    predictor = MLRiskPredictor()
    await predictor.start()

    # Predictions are automatically integrated with risk engine
"""

import os
import json
import logging
import asyncio
from datetime import datetime, timezone, timedelta
from typing import Optional, Dict, Any, List, Callable
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
import threading

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Import risk prediction model
try:
    from ml.risk_prediction_model import RiskPredictionModel, RiskPrediction, ModelConfig
    RISK_MODEL_AVAILABLE = True
except ImportError:
    RISK_MODEL_AVAILABLE = False
    logger.warning("Risk prediction model not available")


# =============================================================================
# Data Models
# =============================================================================

class AlertSeverity(Enum):
    """Risk alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class RiskAlert:
    """Risk alert generated by ML predictor."""
    timestamp: datetime
    symbol: str
    alert_type: str
    severity: AlertSeverity
    message: str
    prediction: Optional[RiskPrediction] = None
    threshold_breached: Optional[float] = None
    recommended_action: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'alert_type': self.alert_type,
            'severity': self.severity.value,
            'message': self.message,
            'prediction': self.prediction.to_dict() if self.prediction else None,
            'threshold_breached': self.threshold_breached,
            'recommended_action': self.recommended_action,
        }


@dataclass
class RiskLimits:
    """Dynamic risk limits based on ML predictions."""
    symbol: str
    max_position_size: float
    max_notional: float
    var_limit_1d: float
    drawdown_limit: float
    updated_at: datetime
    confidence: float  # Model confidence in these limits

    def to_dict(self) -> Dict[str, Any]:
        return {
            'symbol': self.symbol,
            'max_position_size': self.max_position_size,
            'max_notional': self.max_notional,
            'var_limit_1d': self.var_limit_1d,
            'drawdown_limit': self.drawdown_limit,
            'updated_at': self.updated_at.isoformat(),
            'confidence': self.confidence,
        }


@dataclass
class PredictorConfig:
    """Configuration for ML risk predictor."""
    model_path: Optional[str] = None
    update_interval_seconds: int = 60
    lookback_days: int = 252
    var_threshold_warning: float = -0.02  # 2% loss
    var_threshold_critical: float = -0.05  # 5% loss
    drawdown_threshold_warning: float = -0.05
    drawdown_threshold_critical: float = -0.10
    position_scaling_enabled: bool = True
    alert_cooldown_seconds: int = 300  # 5 minutes between same alerts


# =============================================================================
# ML Risk Predictor
# =============================================================================

class MLRiskPredictor:
    """
    Integrates ML risk predictions with the real-time risk engine.

    Responsibilities:
    - Periodic risk prediction updates
    - Dynamic risk limit adjustment
    - Alert generation for high-risk scenarios
    - Position sizing recommendations
    - Integration with monitoring dashboard

    Example:
        predictor = MLRiskPredictor()
        await predictor.start()

        # Get current risk assessment
        assessment = predictor.get_risk_assessment('AAPL')

        # Get position sizing recommendation
        max_size = predictor.get_max_position_size('AAPL', portfolio_value=100000)
    """

    def __init__(self, config: Optional[PredictorConfig] = None):
        """
        Initialize the ML risk predictor.

        Args:
            config: Predictor configuration
        """
        self.config = config or PredictorConfig()

        # Risk prediction model
        self._model: Optional[RiskPredictionModel] = None

        # State
        self._predictions: Dict[str, List[RiskPrediction]] = {}
        self._risk_limits: Dict[str, RiskLimits] = {}
        self._alerts: List[RiskAlert] = []
        self._alert_history: Dict[str, datetime] = {}  # For cooldown

        # Historical data cache
        self._data_cache: Dict[str, pd.DataFrame] = {}

        # Callbacks
        self._on_prediction_callbacks: List[Callable] = []
        self._on_alert_callbacks: List[Callable] = []
        self._on_limit_update_callbacks: List[Callable] = []

        # Control
        self._running = False
        self._update_task: Optional[asyncio.Task] = None
        self._lock = asyncio.Lock()

        # Initialize model
        self._initialize_model()

        logger.info("MLRiskPredictor initialized")

    def _initialize_model(self) -> None:
        """Initialize the risk prediction model."""
        if not RISK_MODEL_AVAILABLE:
            logger.warning("Risk model not available, using fallback")
            return

        try:
            self._model = RiskPredictionModel(use_deep_learning=True)

            # Load pre-trained model if available
            if self.config.model_path and Path(self.config.model_path).exists():
                self._model.load(self.config.model_path)
                logger.info(f"Loaded risk model from {self.config.model_path}")

        except Exception as e:
            logger.error(f"Failed to initialize risk model: {e}")

    async def start(self) -> None:
        """Start the risk predictor."""
        self._running = True
        self._update_task = asyncio.create_task(self._update_loop())
        logger.info("ML Risk Predictor started")

    async def stop(self) -> None:
        """Stop the risk predictor."""
        self._running = False

        if self._update_task:
            self._update_task.cancel()
            try:
                await self._update_task
            except asyncio.CancelledError:
                pass

        logger.info("ML Risk Predictor stopped")

    async def _update_loop(self) -> None:
        """Periodic update loop for predictions."""
        while self._running:
            try:
                await asyncio.sleep(self.config.update_interval_seconds)

                # Update predictions for all tracked symbols
                for symbol in list(self._data_cache.keys()):
                    await self._update_prediction(symbol)

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Prediction update error: {e}")

    async def _update_prediction(self, symbol: str) -> None:
        """Update risk prediction for a symbol."""
        if symbol not in self._data_cache:
            return

        async with self._lock:
            try:
                data = self._data_cache[symbol]

                if self._model and self._model._is_fitted:
                    predictions = self._model.predict(data, symbol=symbol)
                else:
                    predictions = self._compute_fallback_predictions(data, symbol)

                # Store predictions
                self._predictions[symbol] = predictions

                # Update risk limits
                self._update_risk_limits(symbol, predictions)

                # Check for alerts
                self._check_alerts(symbol, predictions)

                # Notify callbacks
                for callback in self._on_prediction_callbacks:
                    try:
                        if asyncio.iscoroutinefunction(callback):
                            await callback(symbol, predictions)
                        else:
                            callback(symbol, predictions)
                    except Exception as e:
                        logger.error(f"Prediction callback error: {e}")

            except Exception as e:
                logger.error(f"Prediction update failed for {symbol}: {e}")

    def _compute_fallback_predictions(
        self,
        data: pd.DataFrame,
        symbol: str,
    ) -> List[RiskPrediction]:
        """Compute simple historical predictions when model unavailable."""
        predictions = []
        now = datetime.now(timezone.utc)

        returns = data.get('returns', data.iloc[:, 0])

        for horizon in [1, 5, 21]:
            # Historical VaR
            var_95 = float(np.percentile(returns.dropna(), 5))
            var_99 = float(np.percentile(returns.dropna(), 1))

            # Historical volatility
            vol = float(returns.std() * np.sqrt(252))

            # Historical CVaR
            cvar_95 = float(returns[returns <= var_95].mean())
            cvar_99 = float(returns[returns <= var_99].mean())

            pred = RiskPrediction(
                timestamp=now,
                symbol=symbol,
                horizon=f'{horizon}d',
                var_95=var_95 * np.sqrt(horizon),
                var_99=var_99 * np.sqrt(horizon),
                cvar_95=cvar_95 * np.sqrt(horizon),
                cvar_99=cvar_99 * np.sqrt(horizon),
                max_drawdown=-0.1,  # Simplified
                drawdown_probability=0.1,
                volatility_forecast=vol,
                prediction_uncertainty=vol * 0.2,
            )
            predictions.append(pred)

        return predictions

    def _update_risk_limits(
        self,
        symbol: str,
        predictions: List[RiskPrediction],
    ) -> None:
        """Update dynamic risk limits based on predictions."""
        if not predictions:
            return

        # Use 1-day prediction for limits
        pred_1d = next((p for p in predictions if p.horizon == '1d'), predictions[0])

        # Base limits
        base_position_pct = 0.10  # 10% max position
        base_var_limit = 0.02    # 2% daily VaR limit

        # Scale limits based on predicted risk
        risk_multiplier = min(1.0, base_var_limit / abs(pred_1d.var_95)) if pred_1d.var_95 != 0 else 1.0

        # Add uncertainty penalty
        uncertainty_penalty = 1.0 - min(0.5, pred_1d.prediction_uncertainty)

        effective_multiplier = risk_multiplier * uncertainty_penalty

        limits = RiskLimits(
            symbol=symbol,
            max_position_size=base_position_pct * effective_multiplier,
            max_notional=1000000 * effective_multiplier,  # $1M base
            var_limit_1d=abs(pred_1d.var_95),
            drawdown_limit=abs(pred_1d.max_drawdown),
            updated_at=datetime.now(timezone.utc),
            confidence=1.0 - pred_1d.prediction_uncertainty,
        )

        self._risk_limits[symbol] = limits

        # Notify callbacks
        for callback in self._on_limit_update_callbacks:
            try:
                callback(symbol, limits)
            except Exception as e:
                logger.error(f"Limit update callback error: {e}")

    def _check_alerts(
        self,
        symbol: str,
        predictions: List[RiskPrediction],
    ) -> None:
        """Check predictions and generate alerts if needed."""
        if not predictions:
            return

        pred_1d = next((p for p in predictions if p.horizon == '1d'), predictions[0])
        now = datetime.now(timezone.utc)

        alerts_to_send = []

        # VaR threshold checks
        if pred_1d.var_95 < self.config.var_threshold_critical:
            alert = self._create_alert_if_not_cooling_down(
                symbol=symbol,
                alert_type='var_critical',
                severity=AlertSeverity.CRITICAL,
                message=f"Critical VaR prediction: {pred_1d.var_95:.2%} exceeds {self.config.var_threshold_critical:.2%}",
                prediction=pred_1d,
                threshold_breached=self.config.var_threshold_critical,
                recommended_action="Reduce position size by 50% or implement hedge",
            )
            if alert:
                alerts_to_send.append(alert)

        elif pred_1d.var_95 < self.config.var_threshold_warning:
            alert = self._create_alert_if_not_cooling_down(
                symbol=symbol,
                alert_type='var_warning',
                severity=AlertSeverity.WARNING,
                message=f"Elevated VaR prediction: {pred_1d.var_95:.2%} exceeds {self.config.var_threshold_warning:.2%}",
                prediction=pred_1d,
                threshold_breached=self.config.var_threshold_warning,
                recommended_action="Monitor closely and consider reducing exposure",
            )
            if alert:
                alerts_to_send.append(alert)

        # Drawdown threshold checks
        if pred_1d.max_drawdown < self.config.drawdown_threshold_critical:
            alert = self._create_alert_if_not_cooling_down(
                symbol=symbol,
                alert_type='drawdown_critical',
                severity=AlertSeverity.CRITICAL,
                message=f"Critical drawdown prediction: {pred_1d.max_drawdown:.2%}",
                prediction=pred_1d,
                threshold_breached=self.config.drawdown_threshold_critical,
                recommended_action="Exit position or implement stop-loss",
            )
            if alert:
                alerts_to_send.append(alert)

        # High uncertainty alert
        if pred_1d.prediction_uncertainty > 0.3:
            alert = self._create_alert_if_not_cooling_down(
                symbol=symbol,
                alert_type='high_uncertainty',
                severity=AlertSeverity.INFO,
                message=f"High prediction uncertainty: {pred_1d.prediction_uncertainty:.2%}",
                prediction=pred_1d,
                recommended_action="Consider using wider stop-loss or reduced position",
            )
            if alert:
                alerts_to_send.append(alert)

        # Send alerts
        for alert in alerts_to_send:
            self._alerts.append(alert)
            self._notify_alert(alert)

    def _create_alert_if_not_cooling_down(
        self,
        symbol: str,
        alert_type: str,
        severity: AlertSeverity,
        message: str,
        prediction: RiskPrediction,
        threshold_breached: Optional[float] = None,
        recommended_action: Optional[str] = None,
    ) -> Optional[RiskAlert]:
        """Create alert if cooldown period has passed."""
        alert_key = f"{symbol}:{alert_type}"
        now = datetime.now(timezone.utc)

        last_alert_time = self._alert_history.get(alert_key)
        if last_alert_time:
            elapsed = (now - last_alert_time).total_seconds()
            if elapsed < self.config.alert_cooldown_seconds:
                return None

        self._alert_history[alert_key] = now

        return RiskAlert(
            timestamp=now,
            symbol=symbol,
            alert_type=alert_type,
            severity=severity,
            message=message,
            prediction=prediction,
            threshold_breached=threshold_breached,
            recommended_action=recommended_action,
        )

    def _notify_alert(self, alert: RiskAlert) -> None:
        """Notify alert callbacks."""
        for callback in self._on_alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                logger.error(f"Alert callback error: {e}")

        # Log alert
        log_func = {
            AlertSeverity.INFO: logger.info,
            AlertSeverity.WARNING: logger.warning,
            AlertSeverity.CRITICAL: logger.error,
            AlertSeverity.EMERGENCY: logger.critical,
        }.get(alert.severity, logger.warning)

        log_func(f"Risk Alert [{alert.severity.value}] {alert.symbol}: {alert.message}")

    def update_market_data(
        self,
        symbol: str,
        data: pd.DataFrame,
    ) -> None:
        """
        Update market data cache for a symbol.

        Args:
            symbol: Symbol identifier
            data: DataFrame with OHLCV and/or returns
        """
        # Ensure we have returns
        if 'returns' not in data.columns and 'close' in data.columns:
            data = data.copy()
            data['returns'] = data['close'].pct_change()

        self._data_cache[symbol] = data.tail(self.config.lookback_days)

    def get_risk_assessment(self, symbol: str) -> Optional[Dict[str, Any]]:
        """
        Get current risk assessment for a symbol.

        Returns:
            Dictionary with predictions, limits, and recent alerts
        """
        if symbol not in self._predictions:
            return None

        predictions = self._predictions[symbol]
        limits = self._risk_limits.get(symbol)
        recent_alerts = [
            a for a in self._alerts[-100:]
            if a.symbol == symbol
        ]

        return {
            'symbol': symbol,
            'predictions': [p.to_dict() for p in predictions],
            'risk_limits': limits.to_dict() if limits else None,
            'recent_alerts': [a.to_dict() for a in recent_alerts[-10:]],
            'last_updated': predictions[0].timestamp.isoformat() if predictions else None,
        }

    def get_max_position_size(
        self,
        symbol: str,
        portfolio_value: float,
        current_position: float = 0.0,
    ) -> float:
        """
        Get recommended maximum position size.

        Args:
            symbol: Symbol identifier
            portfolio_value: Total portfolio value
            current_position: Current position size (in dollars)

        Returns:
            Maximum position size in dollars
        """
        if not self.config.position_scaling_enabled:
            return portfolio_value * 0.10  # Default 10%

        limits = self._risk_limits.get(symbol)
        if not limits:
            return portfolio_value * 0.10

        # Calculate max based on limits
        max_from_pct = portfolio_value * limits.max_position_size
        max_from_notional = limits.max_notional
        max_from_var = portfolio_value * limits.var_limit_1d * 10  # VaR budget

        # Take minimum
        max_size = min(max_from_pct, max_from_notional, max_from_var)

        # Account for current position
        available = max_size - abs(current_position)

        return max(0, available)

    def get_portfolio_risk(
        self,
        positions: Dict[str, float],
        portfolio_value: float,
    ) -> Dict[str, Any]:
        """
        Calculate aggregate portfolio risk from ML predictions.

        Args:
            positions: Dictionary of symbol to position size
            portfolio_value: Total portfolio value

        Returns:
            Dictionary with portfolio-level risk metrics
        """
        if not positions:
            return {
                'portfolio_var_95': 0.0,
                'portfolio_var_99': 0.0,
                'concentration_risk': 0.0,
                'high_risk_exposure': 0.0,
            }

        # Collect individual risks
        weighted_var_95 = 0.0
        weighted_var_99 = 0.0
        high_risk_exposure = 0.0

        for symbol, position_value in positions.items():
            weight = abs(position_value) / portfolio_value
            preds = self._predictions.get(symbol, [])

            if preds:
                pred_1d = next((p for p in preds if p.horizon == '1d'), preds[0])
                weighted_var_95 += weight * abs(pred_1d.var_95)
                weighted_var_99 += weight * abs(pred_1d.var_99)

                if pred_1d.var_95 < self.config.var_threshold_warning:
                    high_risk_exposure += weight

        # Concentration risk (HHI)
        weights = [abs(v) / portfolio_value for v in positions.values()]
        concentration_risk = sum(w ** 2 for w in weights)

        return {
            'portfolio_var_95': weighted_var_95,
            'portfolio_var_99': weighted_var_99,
            'concentration_risk': concentration_risk,
            'high_risk_exposure': high_risk_exposure,
            'position_count': len(positions),
        }

    def train_model(
        self,
        training_data: Dict[str, pd.DataFrame],
        validation_split: float = 0.2,
    ) -> Dict[str, Any]:
        """
        Train or retrain the risk prediction model.

        Args:
            training_data: Dictionary of symbol to historical data
            validation_split: Fraction for validation

        Returns:
            Training metrics
        """
        if not self._model:
            logger.error("No model available for training")
            return {'error': 'No model available'}

        # Combine data from all symbols
        combined_data = pd.concat(training_data.values(), ignore_index=True)

        # Train
        metrics = self._model.fit(combined_data, validation_split=validation_split)

        # Save if path configured
        if self.config.model_path:
            self._model.save(self.config.model_path)

        return metrics

    def on_prediction(self, callback: Callable) -> None:
        """Register callback for prediction updates."""
        self._on_prediction_callbacks.append(callback)

    def on_alert(self, callback: Callable) -> None:
        """Register callback for risk alerts."""
        self._on_alert_callbacks.append(callback)

    def on_limit_update(self, callback: Callable) -> None:
        """Register callback for limit updates."""
        self._on_limit_update_callbacks.append(callback)

    def get_stats(self) -> Dict[str, Any]:
        """Get predictor statistics."""
        return {
            'tracked_symbols': len(self._data_cache),
            'predictions_cached': len(self._predictions),
            'limits_set': len(self._risk_limits),
            'total_alerts': len(self._alerts),
            'model_fitted': self._model._is_fitted if self._model else False,
            'running': self._running,
        }
