# QUANT INDUSTRY Backend Utilities
from .errors import (
    APIError,
    AuthenticationError,
    ConfigurationError,
    DataError,
    NotFoundError,
    RateLimitError,
    ServiceUnavailableError,
    ValidationError,
    api_error_handler,
    error_response,
    handle_endpoint_errors,
    safe_get,
    success_response,
)
from .retry import (
    CircuitBreaker,
    CircuitBreakerOpenError,
    RetryableOperation,
    RetryConfig,
    async_retry,
    retry,
)
from .structured_logging import (
    LogComponent,
    LogLevel,
    LogContext,
    PerformanceMetric,
    ComponentLogger,
    StructuredFormatter,
    get_component_logger,
    configure_structured_logging,
    timed_operation,
    # Convenience loggers
    api_logger,
    data_logger,
    trading_logger,
    risk_logger,
    brain_logger,
    execution_logger,
    ws_logger,
    health_logger,
)
from .timezone import (
    UTC,
    EASTERN,
    utc_now,
    to_utc,
    to_eastern,
    from_timestamp,
    to_timestamp,
    is_market_hours,
    is_premarket,
    is_afterhours,
    get_market_open_time,
    get_market_close_time,
    format_iso,
    parse_iso,
)

__all__ = [
    # Errors
    "APIError",
    "NotFoundError",
    "ValidationError",
    "ServiceUnavailableError",
    "RateLimitError",
    "DataError",
    "AuthenticationError",
    "ConfigurationError",
    "error_response",
    "success_response",
    "handle_endpoint_errors",
    "api_error_handler",
    "safe_get",
    # Retry
    "retry",
    "async_retry",
    "RetryConfig",
    "RetryableOperation",
    "CircuitBreaker",
    "CircuitBreakerOpenError",
    # Structured Logging
    "LogComponent",
    "LogLevel",
    "LogContext",
    "PerformanceMetric",
    "ComponentLogger",
    "StructuredFormatter",
    "get_component_logger",
    "configure_structured_logging",
    "timed_operation",
    "api_logger",
    "data_logger",
    "trading_logger",
    "risk_logger",
    "brain_logger",
    "execution_logger",
    "ws_logger",
    "health_logger",
    # Timezone utilities (ALWAYS use utc_now() instead of datetime.now())
    "UTC",
    "EASTERN",
    "utc_now",
    "to_utc",
    "to_eastern",
    "from_timestamp",
    "to_timestamp",
    "is_market_hours",
    "is_premarket",
    "is_afterhours",
    "get_market_open_time",
    "get_market_close_time",
    "format_iso",
    "parse_iso",
]
